--[[
    GD50
    Zelda Protector

    -- constants --

    Author: Will Dong
    willyiam723@gmail.com
]]

VIRTUAL_WIDTH = 384
VIRTUAL_HEIGHT = 216

WINDOW_WIDTH = 1280
WINDOW_HEIGHT = 720

TILE_SIZE = 16

--
-- entity constants
--
PROTECTOR_WALK_SPEED = 0
PROTECTOR_HAMMER_PRICE = 50
PROTECTOR_CROSSBOW_PRICE = 100
PROTECTOR_ROCKETS_PRICE = 150

PROTECTOR_HAMMER_ATTACK = 1
PROTECTOR_CROSSBOW_ATTACK = 2
PROTECTOR_ROCKETS_ATTACK = 3

ENEMY_WALK_SPEED_LEVEL_ONE = 10
ENEMY_WALK_SPEED_LEVEL_TWO = 20
ENEMY_WALK_SPEED_LEVEL_THREE = 30
ENEMY_WALK_SPEED_LEVEL_FOUR = 40

REWARD_LEVEL_ONE_ENEMY = 5
REWARD_LEVEL_TWO_ENEMY = 10
REWARD_LEVEL_THREE_ENEMY = 20
REWARD_LEVEL_FOUR_ENEMY = 30

--
-- object constants
--
PROJECTILE_FIRE_SPEED = 100

--
-- map constants
--
MAP_WIDTH = VIRTUAL_WIDTH / TILE_SIZE - 2
MAP_HEIGHT = math.floor(VIRTUAL_HEIGHT / TILE_SIZE) - 2

MAP_RENDER_OFFSET_X = (VIRTUAL_WIDTH - (MAP_WIDTH * TILE_SIZE)) / 2
MAP_RENDER_OFFSET_Y = (VIRTUAL_HEIGHT - (MAP_HEIGHT * TILE_SIZE)) / 2

--
-- tile IDs
--
TILE_TOP_LEFT_CORNER = 73
TILE_TOP_RIGHT_CORNER = 75
TILE_BOTTOM_LEFT_CORNER = 89
TILE_BOTTOM_RIGHT_CORNER = 91

TILE_EMPTY = 85

TILE_FLOORS = {46, 47}

TILE_TOP_WALLS = {74}
TILE_BOTTOM_WALLS = {90}
TILE_LEFT_WALLS = {65}
TILE_RIGHT_WALLS = {66}

TILE_START = 62
TILE_ENEMY_TRACK = 45
TILE_FINISH = 42